### ISSUE TITLE
World destruction with symmetric relationship and child causes assertion

### ISSUE THREAD

**Issue by awest03** [SanderMertens/flecs#1212]
**Describe the bug**
When a world's destructor is called (C++ api), an assertion (`fatal: entity.c: 3893: assert: entity != 0 INVALID_PARAMETER`) fails if there is an entity which is a child of another entity and has a symmetric relationship with another entity, that is or is not a child of the same entity.

**To Reproduce**
This code will trigger the bug:
```cpp
#include <flecs.h>

struct Buddies {};

int main()
{
    flecs::world ecs;

    ecs.component<Buddies>().add(flecs::Symmetric);

    flecs::entity idk = ecs.entity("Idk");
    flecs::entity bob = ecs.entity("Bob")
        .child_of(idk);
    ecs.entity("Alice")
        .child_of(idk)
        .add<Buddies>(bob);

    return 0;
}
```

**Expected behavior**
No assertion

**Additional context**
- Fedora Linux 40
- gcc version 14.1.1 20240522 (Red Hat 14.1.1-4) (GCC)
- flecs v4 branch (haven't tested v3)
- Meson build system 1.4.0

**Comment by SanderMertens** [comment]
Fixed on the v4 branch

**Comment by awest03** [comment]
Thanks, it looks like the bug may still be there as the code I posted above still doesn't work on the latest v4 branch, if I add:
```cpp
ecs.remove_all<Buddies>(flecs::Wildcard);
```
before exiting there isn't a problem, so definitely still related to the symmetric relationship

**Comment by SanderMertens** [comment]
Second attempt, should be fixed now :)

**Comment by awest03** [comment]
Thank you! Seems to be working for me now
