### ISSUE TITLE
EcsSparse doesn't apply to pair

### ISSUE THREAD

**Issue by codehz** [SanderMertens/flecs#1492]
**Describe the bug**
see below

**To Reproduce**
```c
#include "flecs.h"

ECS_STRUCT(SparseTest, {
  int32_t value;
});

int main() {
  ecs_world_t *ecs = ecs_init();

  ECS_TAG(ecs, MyTag);
  ECS_META_COMPONENT(ecs, SparseTest);
  ecs_add_id(ecs, ecs_id(SparseTest), EcsSparse);

  ecs_entity_t e1 = ecs_new(ecs);
  ecs_set_pair_second(ecs, e1, ecs_id(MyTag), SparseTest, {});

  ECS_QUERY(ecs, QueryTest, (MyTag, SparseTest));

  ecs_iter_t iter = ecs_query_iter(ecs, QueryTest);

  while (ecs_iter_next(&iter)) {
    for (int i = 0; i < iter.count; i++) {
      ecs_field_at(&iter, SparseTest, 0, i);
    }
  }

  ecs_fini(ecs);
}
```

got error: 
```
fatal: flecs.c: 12090: assert: (idr->flags & EcsIdIsSparse) use ecs_field to access fields for non-sparse components (INVALID_OPERATION)
1   test                                0x00000001041ee2c8 flecs_log_msg + 1676
2   test                                0x0000000104214134 ecs_printv_ + 212
3   test                                0x00000001041c72dc ecs_log_ + 100
4   test                                0x00000001041bc22c ecs_assert_log_ + 168
5   test                                0x00000001041df3ec ecs_field_at_w_size + 1100
6   test                                0x00000001041b3858 main + 1136
7   dyld                                0x0000000188774274 start + 2840
fish: Job 1, './test' terminated by signal SIGABRT (Abort)
```

**Expected behavior**
sparse should work

**Additional context**
version: 243616b

**Comment by SanderMertens** [comment]
Fixed!

**Comment by codehz** [comment]
@SanderMertens it still crash when the pair is added **AFTER** the system/query is created
example:

```c
#include "flecs.h"

ECS_STRUCT(SparseTest, { int32_t value; });

int main() {
  ecs_world_t *ecs = ecs_init();

  ECS_TAG(ecs, MyTag);
  ECS_META_COMPONENT(ecs, SparseTest);
  ecs_add_id(ecs, ecs_id(SparseTest), EcsSparse);

  ECS_QUERY(ecs, QueryTest, [in](MyTag, SparseTest));

  ecs_entity_t e1 = ecs_new(ecs);
  ecs_set_pair_second(ecs, e1, ecs_id(MyTag), SparseTest, {});

  ecs_iter_t iter = ecs_query_iter(ecs, QueryTest);

  while (ecs_iter_next(&iter)) {
    for (int i = 0; i < iter.count; i++) {
      SparseTest *test = ecs_field_at(&iter, SparseTest, 0, i);
      printf("%d\n", test->value);
    }
  }

  ecs_fini(ecs);
}
```

**Comment by SanderMertens** [comment]
Fixed! (again)
