### ISSUE TITLE
Crash on filter fini when using named terms

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#537]
**Describe the bug**
Exception 0x80000003 is triggered in `ecs_term_fini` 
```C
void ecs_term_fini(
    ecs_term_t *term)
{
    ecs_os_free(term->pred.name);
    ecs_os_free(term->subj.name); // <--- here
    ecs_os_free(term->obj.name);
    ecs_os_free(term->name);

    term->pred.name = NULL;
    term->subj.name = NULL;
    term->obj.name = NULL;
    term->name = NULL;
}
```
**To Reproduce**
```c++
{
    flecs::world World;
    World.system<const Config>("MySystem")
        .arg(1).subj().name("MySystem")
        .iter([](flecs::iter& Iter, const Config* Config)
        {
            printf("Hit\n");
        })
        .set<Config>({1});
}
```

**Expected behavior**
No Crash

**Additional context**
can be worked around by using `.arg(1).subj().name(ecs_os_strdup("MySystem"))`

**Comment by SanderMertens** [comment]
Fixed!

**Comment by BHolman-LBI** [comment]
This still happens when using `.var("name")` to name a variable term.
